### ISSUE TITLE
CHGCAR plot error

### ISSUE THREAD

**Issue by alejandrogallo** [PytLab/VASPy#5]
I get the following error

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    a = ChgCar()
  File "/home/gallo/software/VASPy/vaspy/electro.py", line 549, in __init__
    ElfCar.__init__(self, filename)
  File "/home/gallo/software/VASPy/vaspy/electro.py", line 268, in __init__
    super(ElfCar, self).__init__(filename)
  File "/home/gallo/software/VASPy/vaspy/atomco.py", line 357, in __init__
    self.load()
  File "/home/gallo/software/VASPy/vaspy/electro.py", line 289, in load
    datalist = line2list(line)
  File "/home/gallo/software/VASPy/vaspy/functions.py", line 20, in line2list
    datalist = [dtype(i) for i in strlist if i != '']
  File "/home/gallo/software/VASPy/vaspy/functions.py", line 20, in <listcomp>
    datalist = [dtype(i) for i in strlist if i != '']
ValueError: could not convert string to float: 'augmentation'

```

witht the following script

```python
import vaspy

from vaspy.electro import ChgCar

a = ChgCar()

a.plot_contour3d()


```

**Comment by PytLab** [comment]
Hi, is it convenient for you to show me the CHGCAR file?

**Comment by alejandrogallo** [comment]
Sure, here is one example:
[chgcar.log](https://github.com/PytLab/VASPy/files/1571703/chgcar.log)

Thanks!

**Comment by PytLab** [comment]
This bug has the same root cause as issue #15. The `line2list` function in `functions.py` failed to parse non-numeric strings like "augmentation" in CHGCAR files.

The fix has been applied in two places:
1. `functions.py:line2list` — now gracefully skips non-numeric tokens instead of crashing
2. `electro.py:ElfCar.load()` — now reads exactly `NGX*NGY*NGZ` data values and stops, avoiding the "augmentation occupancies" section

Both fixes will be included in the next release.
